[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "k1mch1", email = "jingluy123@gmail.com" }
]
requires-python = ">=3.11.13"
dependencies = [
    "marimo>=0.24.2",
]

[project.scripts]
scripts = "scripts:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
